### ISSUE TITLE
Script ignores acpi_video0 settings

### ISSUE THREAD

**Issue by Zzooouhh** [antipatico/backlight-openrc#1]
Using Manjaro-openrc Xfce on a Lenovo T420 brings up issues with this script; I have two backlight folders in /sys/class/backlight/: acpi_video0 and intel_backlight. After including it in rc-update, backlight-openrc on shutdown only managed to copy intel_backlight, which means that while on reboot it updates the _initial_ backlight setting to the previous value, but pressing the brightness up/down keys shoots it back up as if the max values were set.

A quick check on the backlight files in /sys/class/ reveals that intel_backlight gets restored properly while acpi_video0's values are reset to the maximum of 15 on every bootup. I've also tried manually creating a new acpi_video0-backlight-old file in the /var/cache/backlight/, but the script doesn't manage to copy it either.

A workaround for me was including a simple cp one-liner in rc.local (the acpi_video0-brightness-old file was custom created), which appears to recognize acpi_video0:
cp "/var/cache/backlight/acpi_video0-brightness-old" "/sys/class/backlight/acpi_video0/brightness"
(repeat for other backlights)
And since Manjaro also has an rc.local.shutdown, an equivalent one-liner for the opposite direction went there too.

**Comment by antipatico** [comment]
I've left openrc since I have no time to mantain it .
If you want to send me a pull request I'll merge.
