### ISSUE TITLE
Update /sbin/openrc-run with /usr/bin/openrc-run

### ISSUE THREAD

**Issue by Megver83** [antipatico/backlight-openrc#3]
I tested in my laptop this script, and didn't worked. Then I solved it by just replacing in the first line /sbin/openrc-run with /usr/bin/openrc-run. I also noted that all /etc/init.d scripts begin with /usr/bin and none with /sbin (although it's a symlink to /usr/bin, but still doesn't work).

**Comment by antipatico** [comment]
I'll fix it, even if I haven't had an openrc system in a long time.

**Comment by antipatico** [comment]
I've [looked at it ](http://manpages.ubuntu.com/manpages/wily/man8/openrc-run.8.html)and it seems like it still is /sbin/openrc-run .
No patch.
